// Generated by bench2verilog.py
module multiplexer_2x1(
    d0, d1, s0, y
);

  input  d0, d1, s0;
  output y;
  wire   CONST0, CONST1, n_not_d0, n_not_d1, n_not_s0, p_y_0, p_y_1, p_y_2, p_y_3;

  assign CONST0 = (s0 & n_not_s0);
  assign CONST1 = (s0 | n_not_s0);
  assign n_not_d0 = ~(d0);
  assign n_not_d1 = ~(d1);
  assign n_not_s0 = ~(s0);
  assign p_y_0 = (n_not_s0 & d0 & n_not_d1);
  assign p_y_1 = (n_not_s0 & d0 & d1);
  assign p_y_2 = (s0 & n_not_d0 & d1);
  assign p_y_3 = (s0 & d0 & d1);
  assign y = (p_y_0 | p_y_1 | p_y_2 | p_y_3);

endmodule
